#!/bin/sh
: ${GIT_AUTOPUSH_BRANCHES:=main}
: ${GIT_AUTOPUSH_REMOTES:=origin}

if [ -f $BASE_DIR/.githooks.conf ]; then
    . $BASE_DIR/.githooks.conf
fi

echo "Pushing to remote repository..."
current_branch="$(git rev-parse --abbrev-ref HEAD)"
if echo "$GIT_AUTOPUSH_BRANCHES" | grep -wq "$current_branch"; then
    echo "[post-commit:autopush] Pusching $current_branch to remote repository..." >&2
    for remote in $GIT_AUTOPUSH_REMOTES; do
        echo "[post-commit:autopush] Pushing to remote '$remote'..." >&2
        git push "$remote" "$current_branch" && echo "[post-commit:autopush] Successfully pushed to remote '$remote'." >&2 || {
            echo "[post-commit:autopush] Failed to push to remote '$remote'. Please check your network connection and remote repository settings." >&2
            exit 1
        }
    done
else
    echo "[post-commit:autopush] Branch '$current_branch' is not in the list of branches to autopush: $GIT_AUTOPUSH_BRANCHES. Skipping push..." >&2
fi
