#!/bin/sh

cd "$BASE_DIR" || exit 1

: ${GIT_TESTS_KEEPDB:=0}
if [ -f .githooks.conf ]; then
    . .githooks.conf
fi

echo "[pre-commit:run-tests] Running tests with GIT_TESTS_KEEPDB=$GIT_TESTS_KEEPDB..."

if [ "$GIT_TESTS_KEEPDB" -eq 1 ]; then
    poetry run python manage.py test --keepdb --parallel
else
    poetry run python manage.py test --parallel
fi
rc=$?
if [ $rc -ne 0 ]; then
    echo "[pre-commit:run-tests] Tests failed with exit code $rc."
    exit $rc
fi

echo "[pre-commit:run-tests] Tests passed successfully."
exit 0
