FROM docker.io/library/debian:trixie-slim
ENV DEBUG=1
ENV PYTHONUNBUFFERED=1
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHON_POETRY=1
ENV VIRTUAL_ENV=.venv
ENV CONTAINERIZED=1
ENV MEDIA_ROOT=/data/media
ENV STATIC_ROOT=/data/static
ENV VIRTUAL_ENV=/venv
ENV HTTP_PORT=8000
ENV HTTPS_PORT=8001
ENV APACHE_ENABLED=1
ENV UWSGI_ENABLED=1
ENV APACHE_UWSGI_ENABLED=0
ENV APACHE_HTTP_ENABLED=1
ENV APACHE_HTTPS_ENABLED=0
ENV PATH=/venv/bin:/usr/sbin:$PATH
VOLUME /data
RUN apt-get update \
    && apt-get upgrade -y \
    && apt-get install -y --no-install-recommends \
        acl \
        build-essential \
        python3-venv \
        python3-dev \
        python3-pip \
        python3-setuptools \
        python3-wheel \
        python3-flake8 \
        python3-poetry \
        python-is-python3 \
        gettext \
        libreadline-dev \
        postgresql-client \
        libpq-dev \
        libmariadb-dev \
        apache2 \
        apache2-utils \
        apache2-bin \
        apache2-dev \
        pkgconf \
        libapache2-mod-wsgi-py3 \
        uwsgi-core \
        uwsgi-plugin-python3 \
    && sh -c "echo 'daemon off;' >> /etc/apache2/apache2.conf" \
    && a2enmod wsgi ssl rewrite auth_form \
    && a2enconf security \
    && rm -rf /etc/apache2/sites-enabled /etc/apache2/sites-available \
    && ln -s /data/.httpd/sites-available /etc/apache2/sites-available \
    && ln -s /data/.httpd/sites-enabled /etc/apache2/sites-enabled \
    && rm -rf /var/lib/apt/lists/*
ENV PATH="/venv/bin:/usr/sbin:$PATH"
RUN mkdir -p /venv /app /data/media /data/static /data/.httpd \
    && ln -s /venv /app/.venv
COPY . /app
WORKDIR /app
RUN poetry lock \
    && poetry config virtualenvs.in-project true \
    && cp /app/httpd/options-ssl-apache.conf /etc/apache2/options-ssl.conf \
    && if [ -d /app/django_project/local_settings ]; then rm -rf /app/django_project/local_settings; fi \
    && ln -s /data/config /app/django_project/local_settings \
    && poetry install --no-interaction --all-groups --no-root \
    && chmod +x /app/run.sh \
    && ln -s '/app/run.sh' /usr/local/bin/run.sh \
    && ln -s './run.sh' /usr/local/bin/run \
    && ln -s './run.sh' /usr/local/bin/entrypoint.sh



EXPOSE $HTTP_PORT/tcp $HTTPS_PORT/tcp

ENTRYPOINT ["/app/run.sh"]
