# Generated by Django 6.0.5 on 2026-06-04 17:25

import django.db.models.deletion
import django.utils.timezone
import django_tinyuser.models.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='TinyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(blank=True, db_column='email', max_length=254, null=True, unique=True, verbose_name='email address')),
                ('username', models.CharField(db_column='username', max_length=127, unique=True, verbose_name='username')),
                ('is_active', models.BooleanField(db_column='is_active', default=True, verbose_name='active')),
                ('is_staff', models.BooleanField(db_column='is_staff', default=False, verbose_name='staff status')),
                ('is_superuser', models.BooleanField(db_column='is_superuser', default=False, verbose_name='superuser status')),
                ('is_system_user', models.BooleanField(db_column='is_system_user', default=False, verbose_name='system user')),
                ('is_verified', models.BooleanField(db_column='is_verified', default=False, verbose_name='verified')),
                ('joined_at', models.DateTimeField(db_column='joined_at', default=django.utils.timezone.now, verbose_name='joined at')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'db_table': 'tinyuser_user',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='FriendGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description_type', models.TextField(choices=[('text', 'Text'), ('markdown', 'Markdown'), ('bbcode', 'BBCode')], default='text', verbose_name='description type')),
                ('description', models.TextField(blank=True)),
                ('members', models.ManyToManyField(related_name='friend_groups', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_friend_groups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'friend group',
                'verbose_name_plural': 'friend groups',
                'db_table': 'tinyuser_friend_group',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Friendship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user1_is_initiator', models.BooleanField(db_column='is_initiator', default=False, verbose_name='friendship initiator')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status_data', models.CharField(db_column='status', default='pending', max_length=20, verbose_name='friendship status')),
                ('rejected_reason', models.TextField(blank=True, db_column='rejected_reason', null=True, verbose_name='rejection reason')),
                ('blocked_status_data', models.CharField(db_column='blocked_status', default='not_blocked', max_length=20, verbose_name='friendship blocked status')),
                ('blocked_reason_user1', models.TextField(blank=True, db_column='blocked_reason_user1', max_length=500, null=True, verbose_name='blocking reason')),
                ('blocked_reason_user2', models.TextField(blank=True, db_column='blocked_reason_user2', max_length=500, null=True, verbose_name='blocking reason')),
                ('user1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendships_initiated', to=settings.AUTH_USER_MODEL)),
                ('user2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendships_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user friendship',
                'verbose_name_plural': 'user friendships',
                'db_table': 'tinyuser_friendship',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='FriendshipRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status_data', models.CharField(db_column='status', default='pending', max_length=20, verbose_name='friendship request status')),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendship_requests_sent', to=settings.AUTH_USER_MODEL)),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendship_requests_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'friendship request',
                'verbose_name_plural': 'friendship requests',
                'db_table': 'tinyuser_friendship_request',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TinyUserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=30)),
                ('last_name', models.CharField(blank=True, max_length=30)),
                ('bio', models.TextField(blank=True, verbose_name='biography (Markdown supported)')),
                ('location', models.CharField(blank=True, max_length=255, verbose_name='location')),
                ('website', models.URLField(blank=True, verbose_name='website')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='birth date')),
                ('profile_picture_small', django_tinyuser.models.fields.RestrictedImageField(blank=True, null=True, upload_to='profile_pictures/', verbose_name='small profile picture')),
                ('profile_picture_medium', django_tinyuser.models.fields.RestrictedImageField(blank=True, null=True, upload_to='profile_pictures/', verbose_name='medium profile picture')),
                ('profile_picture_large', django_tinyuser.models.fields.RestrictedImageField(blank=True, null=True, upload_to='profile_pictures/', verbose_name='large profile picture')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user profile',
                'verbose_name_plural': 'user profiles',
                'db_table': 'tinyuser_profile',
                'managed': True,
            },
        ),
        migrations.AddIndex(
            model_name='tinyuser',
            index=models.Index(fields=['email'], name='email_idx'),
        ),
        migrations.AddIndex(
            model_name='tinyuser',
            index=models.Index(fields=['username'], name='username_idx'),
        ),
        migrations.AddConstraint(
            model_name='tinyuser',
            constraint=models.UniqueConstraint(condition=models.Q(('email__isnull', False)), fields=('email',), name='unique_email'),
        ),
        migrations.AddConstraint(
            model_name='tinyuser',
            constraint=models.CheckConstraint(condition=models.Q(('email__isnull', True), ('is_system_user', False), _connector='OR'), name='email_not_system_user'),
        ),
        migrations.AddIndex(
            model_name='friendgroup',
            index=models.Index(fields=['name'], name='tinyuser_fr_name_bc5900_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='friendgroup',
            unique_together={('user', 'name')},
        ),
        migrations.AddIndex(
            model_name='friendship',
            index=models.Index(fields=['user1'], name='friendship_user1_idx'),
        ),
        migrations.AddIndex(
            model_name='friendship',
            index=models.Index(fields=['user2'], name='friendship_user2_idx'),
        ),
        migrations.AddIndex(
            model_name='friendship',
            index=models.Index(fields=['user1', 'user2'], name='friendship_idx'),
        ),
        migrations.AddConstraint(
            model_name='friendship',
            constraint=models.CheckConstraint(condition=models.Q(('user1', models.F('user2')), _negated=True), name='no_self_friendship'),
        ),
        migrations.AddConstraint(
            model_name='friendship',
            constraint=models.CheckConstraint(condition=models.Q(('user1', models.F('user2')), ('user2', models.F('user1')), _negated=True), name='no_duplicate'),
        ),
        migrations.AlterUniqueTogether(
            name='friendship',
            unique_together={('user1', 'user2')},
        ),
        migrations.AddIndex(
            model_name='friendshiprequest',
            index=models.Index(fields=['from_user'], name='request_from_user_idx'),
        ),
        migrations.AddIndex(
            model_name='friendshiprequest',
            index=models.Index(fields=['to_user'], name='request_to_user_idx'),
        ),
        migrations.AddIndex(
            model_name='friendshiprequest',
            index=models.Index(fields=['from_user', 'to_user'], name='request_idx'),
        ),
        migrations.AddConstraint(
            model_name='friendshiprequest',
            constraint=models.CheckConstraint(condition=models.Q(('from_user', models.F('to_user')), _negated=True), name='no_self_request'),
        ),
        migrations.AddConstraint(
            model_name='friendshiprequest',
            constraint=models.CheckConstraint(condition=models.Q(('from_user', models.F('to_user')), ('to_user', models.F('from_user')), _negated=True), name='no_duplicate_request'),
        ),
        migrations.AlterUniqueTogether(
            name='friendshiprequest',
            unique_together={('from_user', 'to_user')},
        ),
        migrations.AddIndex(
            model_name='tinyuserprofile',
            index=models.Index(fields=['user'], name='user_idx'),
        ),
    ]
