# Generated by Django 6.0.5 on 2026-05-22 06:10

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='TinyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(db_column='email_address', max_length=254, unique=True, verbose_name='email address')),
                ('username', models.CharField(db_column='username', max_length=127, unique=True, verbose_name='username')),
                ('is_active', models.BooleanField(db_column='is_active', default=True, verbose_name='active')),
                ('is_staff', models.BooleanField(db_column='is_staff', default=False, verbose_name='staff status')),
                ('is_superuser', models.BooleanField(db_column='is_superuser', default=False, verbose_name='superuser status')),
                ('is_verified', models.BooleanField(db_column='is_verified', default=False, verbose_name='verified')),
                ('joined_at', models.DateTimeField(db_column='joined_at', default=django.utils.timezone.now, verbose_name='joined at')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'db_table': 'tinyuser_user',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TinyUserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=30)),
                ('last_name', models.CharField(blank=True, max_length=30)),
                ('bio', models.TextField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user profile',
                'verbose_name_plural': 'user profiles',
                'db_table': 'tinyuser_profile',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UserFriendGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description_type', models.TextField(choices=[('text', 'Text'), ('markdown', 'Markdown'), ('bbcode', 'BBCode')], default='text', verbose_name='description type')),
                ('description', models.TextField(blank=True)),
                ('members', models.ManyToManyField(related_name='friend_groups', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_friend_groups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'friend group',
                'verbose_name_plural': 'friend groups',
                'db_table': 'tinyuser_friend_group',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UserFriendship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_initiator', models.BooleanField(db_column='is_initiator', default=False, verbose_name='friendship initiator')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status_data', models.CharField(db_column='status', default='pending', max_length=20, verbose_name='friendship status')),
                ('blocked_status_data', models.CharField(db_column='blocked_status', default='not_blocked', max_length=20, verbose_name='friendship blocked status')),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendships_initiated', to=settings.AUTH_USER_MODEL)),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendships_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user friendship',
                'verbose_name_plural': 'user friendships',
                'db_table': 'tinyuser_friendship',
                'managed': True,
            },
        ),
        migrations.AddIndex(
            model_name='tinyuser',
            index=models.Index(fields=['email'], name='email_idx'),
        ),
        migrations.AddIndex(
            model_name='tinyuser',
            index=models.Index(fields=['username'], name='username_idx'),
        ),
        migrations.AddIndex(
            model_name='tinyuserprofile',
            index=models.Index(fields=['user'], name='user_idx'),
        ),
        migrations.AddIndex(
            model_name='userfriendgroup',
            index=models.Index(fields=['name'], name='friend_group_name_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userfriendgroup',
            unique_together={('user', 'name')},
        ),
        migrations.AddIndex(
            model_name='userfriendship',
            index=models.Index(fields=['from_user'], name='from_user_idx'),
        ),
        migrations.AddIndex(
            model_name='userfriendship',
            index=models.Index(fields=['to_user'], name='to_user_idx'),
        ),
        migrations.AddIndex(
            model_name='userfriendship',
            index=models.Index(fields=['from_user', 'to_user'], name='friendship_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userfriendship',
            unique_together={('from_user', 'to_user')},
        ),
    ]
