# Generated by Django 6.0.6 on 2026-06-10 21:14

import django.db.models.deletion
import django.utils.timezone
import django_tinyuser.models.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='TinyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(blank=True, db_column='email', max_length=254, null=True, unique=True, verbose_name='email address')),
                ('username', models.CharField(db_column='username', max_length=127, unique=True, verbose_name='username')),
                ('is_active', models.BooleanField(db_column='is_active', default=True, verbose_name='active')),
                ('is_staff', models.BooleanField(db_column='is_staff', default=False, verbose_name='staff status')),
                ('is_superuser', models.BooleanField(db_column='is_superuser', default=False, verbose_name='superuser status')),
                ('is_system_user', models.BooleanField(db_column='is_system_user', default=False, verbose_name='system user')),
                ('is_verified', models.BooleanField(db_column='is_verified', default=False, verbose_name='verified')),
                ('joined_at', models.DateTimeField(db_column='joined_at', default=django.utils.timezone.now, verbose_name='joined at')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'db_table': 'tinyuser_user',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=30)),
                ('last_name', models.CharField(blank=True, max_length=30)),
                ('bio', models.TextField(blank=True, verbose_name='biography (Markdown supported)')),
                ('location', models.CharField(blank=True, max_length=255, verbose_name='location')),
                ('website', models.URLField(blank=True, verbose_name='website')),
                ('mastodon_url', models.URLField(blank=True, verbose_name='Mastodon profile URL')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='birth date')),
                ('avatar_small', django_tinyuser.models.fields.RestrictedImageField(blank=True, null=True, upload_to='user/avatars/', verbose_name='small profile picture')),
                ('avatar_medium', django_tinyuser.models.fields.RestrictedImageField(blank=True, null=True, upload_to='user/avatars/', verbose_name='medium profile picture')),
                ('avatar_large', django_tinyuser.models.fields.RestrictedImageField(blank=True, null=True, upload_to='user/avatars/', verbose_name='large profile picture')),
                ('avatar_full', django_tinyuser.models.fields.RestrictedImageField(blank=True, null=True, upload_to='user/avatars/', verbose_name='full size profile picture')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user profile',
                'verbose_name_plural': 'user profiles',
                'db_table': 'tinyuser_profile',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UserProfileSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='public', max_length=255, verbose_name='settings type')),
                ('is_forbidden', models.BooleanField(default=True, verbose_name='forbid to view my profile')),
                ('is_public', models.BooleanField(default=False, verbose_name='public')),
                ('is_member_only', models.BooleanField(default=False, verbose_name='member only')),
                ('show_email', models.BooleanField(default=False, verbose_name='show email')),
                ('show_full_name', models.BooleanField(default=False, verbose_name='show full name')),
                ('show_birth_date', models.CharField(choices=[('date', 'date'), ('birthday', 'birthday'), ('no', 'no')], default='no', max_length=31)),
                ('show_website', models.BooleanField(default=True, verbose_name='show website')),
                ('show_mastodon_url', models.BooleanField(default=True, verbose_name='show mastodon url')),
                ('show_bio', models.BooleanField(default=True, verbose_name='show bigraphy')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_tinyuser.userprofile', verbose_name="user's profile")),
            ],
            options={
                'verbose_name': 'profile settings',
                'verbose_name_plural': 'profile settings',
                'db_table': 'tinyuser_profile_settings',
            },
        ),
        migrations.AddIndex(
            model_name='tinyuser',
            index=models.Index(fields=['email'], name='email_idx'),
        ),
        migrations.AddIndex(
            model_name='tinyuser',
            index=models.Index(fields=['username'], name='username_idx'),
        ),
        migrations.AddConstraint(
            model_name='tinyuser',
            constraint=models.UniqueConstraint(condition=models.Q(('email__isnull', False)), fields=('email',), name='unique_email'),
        ),
        migrations.AddConstraint(
            model_name='tinyuser',
            constraint=models.CheckConstraint(condition=models.Q(('email__isnull', True), ('is_system_user', False), _connector='OR'), name='email_not_system_user'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['user'], name='user_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofilesettings',
            index=models.Index(fields=['profile'], name='tinyuser_pr_profile_9242c2_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofilesettings',
            index=models.Index(fields=['type'], name='tinyuser_pr_type_a89184_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofilesettings',
            index=models.Index(fields=['profile', 'type'], name='tinyuser_pr_profile_6b5a0b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userprofilesettings',
            unique_together={('profile', 'type')},
        ),
    ]
