# Generated by Django 6.0.6 on 2026-06-11 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_tinyuser', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tinyuser',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.RenameField(
            model_name='userprofilesettings',
            old_name='is_forbidden',
            new_name='is_enabled',
        ),
        migrations.RemoveField(
            model_name='userprofilesettings',
            name='is_member_only',
        ),
        migrations.AlterField(
            model_name='userprofilesettings',
            name='type',
            field=models.SlugField(default='public', max_length=255, verbose_name='settings type'),
        ),
    ]
