# Generated by Django 6.0.5 on 2026-06-07 02:14

import django_tinyuser.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_tinyuser', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tinyuserprofile',
            old_name='profile_picture_large',
            new_name='avatar_large',
        ),
        migrations.RenameField(
            model_name='tinyuserprofile',
            old_name='profile_picture_medium',
            new_name='avatar_medium',
        ),
        migrations.RenameField(
            model_name='tinyuserprofile',
            old_name='profile_picture_small',
            new_name='avatar_small',
        ),
        migrations.AddField(
            model_name='tinyuserprofile',
            name='avatar_full',
            field=django_tinyuser.models.fields.RestrictedImageField(blank=True, null=True, upload_to='profile_pictures/', verbose_name='full size profile picture'),
        ),
    ]
