# Generated by Django 6.0.6 on 2026-06-11 20:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_tinyuser', '0002_alter_tinyuser_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofilesettings',
            name='is_public',
        ),
        migrations.AddField(
            model_name='userprofilesettings',
            name='show_avatar',
            field=models.BooleanField(default=True, verbose_name='show avatar'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tinyuser_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
