# Generated by Django 6.0.6 on 2026-06-10 17:52

import django_tinyuser.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_tinyuser', '0002_rename_profile_picture_large_tinyuserprofile_avatar_large_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='friendgroup',
            unique_together=None,
        ),
        migrations.RemoveIndex(
            model_name='friendgroup',
            name='tinyuser_fr_name_bc5900_idx',
        ),
        migrations.AlterUniqueTogether(
            name='friendship',
            unique_together=None,
        ),
        migrations.RemoveIndex(
            model_name='friendship',
            name='friendship_user1_idx',
        ),
        migrations.RemoveIndex(
            model_name='friendship',
            name='friendship_user2_idx',
        ),
        migrations.RemoveIndex(
            model_name='friendship',
            name='friendship_idx',
        ),
        migrations.RemoveConstraint(
            model_name='friendship',
            name='no_self_friendship',
        ),
        migrations.RemoveConstraint(
            model_name='friendship',
            name='no_duplicate',
        ),
        migrations.AlterUniqueTogether(
            name='friendshiprequest',
            unique_together=None,
        ),
        migrations.RemoveIndex(
            model_name='friendshiprequest',
            name='request_from_user_idx',
        ),
        migrations.RemoveIndex(
            model_name='friendshiprequest',
            name='request_to_user_idx',
        ),
        migrations.RemoveIndex(
            model_name='friendshiprequest',
            name='request_idx',
        ),
        migrations.RemoveConstraint(
            model_name='friendshiprequest',
            name='no_self_request',
        ),
        migrations.RemoveConstraint(
            model_name='friendshiprequest',
            name='no_duplicate_request',
        ),
        migrations.AddField(
            model_name='tinyuserprofile',
            name='mastodon_url',
            field=models.URLField(blank=True, verbose_name='Mastodon profile URL'),
        ),
        migrations.AlterField(
            model_name='tinyuserprofile',
            name='avatar_full',
            field=django_tinyuser.models.fields.RestrictedImageField(blank=True, null=True, upload_to='user/avatars/', verbose_name='full size profile picture'),
        ),
        migrations.AlterField(
            model_name='tinyuserprofile',
            name='avatar_large',
            field=django_tinyuser.models.fields.RestrictedImageField(blank=True, null=True, upload_to='user/avatars/', verbose_name='large profile picture'),
        ),
        migrations.AlterField(
            model_name='tinyuserprofile',
            name='avatar_medium',
            field=django_tinyuser.models.fields.RestrictedImageField(blank=True, null=True, upload_to='user/avatars/', verbose_name='medium profile picture'),
        ),
        migrations.AlterField(
            model_name='tinyuserprofile',
            name='avatar_small',
            field=django_tinyuser.models.fields.RestrictedImageField(blank=True, null=True, upload_to='user/avatars/', verbose_name='small profile picture'),
        ),
        migrations.RemoveField(
            model_name='friendship',
            name='user1',
        ),
        migrations.RemoveField(
            model_name='friendship',
            name='user2',
        ),
        migrations.RemoveField(
            model_name='friendshiprequest',
            name='from_user',
        ),
        migrations.RemoveField(
            model_name='friendshiprequest',
            name='to_user',
        ),
        migrations.DeleteModel(
            name='FriendGroup',
        ),
        migrations.DeleteModel(
            name='Friendship',
        ),
        migrations.DeleteModel(
            name='FriendshipRequest',
        ),
    ]
