# Generated by Django 6.0.6 on 2026-06-12 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_tinyuser', '0003_remove_userprofilesettings_is_public_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofilesettings',
            name='show_location',
            field=models.BooleanField(default=False, verbose_name='show location'),
        ),
    ]
