# Generated by Django 6.0.6 on 2026-06-22 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_tinyuser', '0004_userprofilesettings_show_location'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='userprofilesettings',
            name='tinyuser_pr_type_a89184_idx',
        ),
        migrations.RemoveIndex(
            model_name='userprofilesettings',
            name='tinyuser_pr_profile_6b5a0b_idx',
        ),
        migrations.RenameField(
            model_name='userprofilesettings',
            old_name='type',
            new_name='key',
        ),
        migrations.AlterUniqueTogether(
            name='userprofilesettings',
            unique_together={('profile', 'key')},
        ),
        migrations.AddField(
            model_name='userprofilesettings',
            name='name',
            field=models.CharField(default='public', max_length=255, verbose_name='Profile name'),
        ),
        migrations.AddIndex(
            model_name='userprofilesettings',
            index=models.Index(fields=['key'], name='tinyuser_pr_key_52bc84_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofilesettings',
            index=models.Index(fields=['profile', 'key'], name='tinyuser_pr_profile_5b15a8_idx'),
        ),
    ]
