"""
Django settings for django_project project.

Generated by 'django-admin startproject' using Django 5.2.13.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from .env import ENV

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = ENV('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!

DEBUG = ENV('DEBUG')

LOCAL_SETTINGS_DIR = BASE_DIR / "django_project" / "local_settings"
_local_settings_file = LOCAL_SETTINGS_DIR / "settings.py"
if _local_settings_file.exists():
    from .local_settings import settings as local_settings
    DEBUG = getattr(local_settings, "DEBUG", ENV("DEBUG"))

ALLOWED_HOSTS = ENV('ALLOWED_HOSTS')

# Application definition

django_apps = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
)

allauth_apps = (
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
)

third_party_apps = [
    'django_extensions',
    'widget_tweaks',
]

project_apps = [
    'django_tinyuser',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'allauth.account.middleware.AccountMiddleware',
]

ROOT_URLCONF = 'django_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django_tinyuser.context_processors.tinyuser',
            ],
        },
    },
]

WSGI_APPLICATION = 'django_project.wsgi.application'
CSS_FRAMEWORK = ENV('CSS_FRAMEWORK').lower()

USE_POSTGRES_SCHEMAS = ENV('USE_POSTGRES_SCHEMAS')
DJANGO_POSTGRES_SCHEMA = ENV('DJANGO_POSTGRES_SCHEMA')
POSTGRES_SCHEMA = ENV('POSTGRES_SCHEMA')
TINYUSER_SHOW_INDEX_PAGE = ENV('TINYUSER_SHOW_INDEX_PAGE')

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

if ENV('DATABASE_CONFIG_METHOD') == 'url':
    DATABASES = {
        'default': ENV.db_url('DATABASE_URL'),
    }
elif ENV('DATABASE_CONFIG_METHOD') in ('postgresql','pgsql', 'postgres', 'psql'):
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': ENV('POSTGRES_DB'),
            'USER': ENV('POSTGRES_USER'),
            'PASSWORD': ENV('POSTGRES_PASSWORD'),
            'HOST': ENV('POSTGRES_HOST'),
            'PORT': ENV('POSTGRES_PORT'),
        }
    }
elif ENV('DATABASE_CONFIG_METHOD') in ('mysql', 'mariadb'):
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': ENV('MYSQL_DB'),
            'USER': ENV('MYSQL_USER'),
            'PASSWORD': ENV('MYSQL_PASSWORD'),
            'HOST': ENV('MYSQL_HOST'),
            'PORT': ENV('MYSQL_PORT'),
        }
    }
elif ENV('DATABASE_CONFIG_METHOD') in ('sqlite','sqlite3'):
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': ENV('SQLITE_DB_NAME'),
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / '.data' / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = ENV('LANGUAGE_CODE', default='en-us')
USE_I18N = ENV('USE_I18N', default=True)

USE_TZ = ENV('USE_TZ', default=True)
TIME_ZONE = ENV('TIME_ZONE', default='UTC')

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

SETTINGS_DIR = Path(__file__).resolve().parent
LOCAL_SETTINGS_DIR = SETTINGS_DIR / "local_settings"
if ENV('CONTAINERIZED'):
    if Path('/etc/django-env').exists():
        ENV.read_env('/etc/django-env')


AUTH_USER_MODEL = 'django_tinyuser.TinyUser'

BASE_TEMPLATE= None

if DEBUG:
    _debug_settings_file = SETTINGS_DIR / "debug_settings.py"
    if _debug_settings_file.exists():
        from .debug_settings import *
    _debug_settings_file = LOCAL_SETTINGS_DIR / "debug_settings.py"
    del _debug_settings_file

    print("Running in DEBUG mode. Debug settings have been applied.")
    third_party_apps += [
        'debug_toolbar',
        'django_browser_reload',
    ]
    MIDDLEWARE.insert(0, 'debug_toolbar.middleware.DebugToolbarMiddleware')
    MIDDLEWARE.insert(0, 'django_browser_reload.middleware.BrowserReloadMiddleware')
else:
    _production_settings_file = SETTINGS_DIR / "production_settings.py"
    if _production_settings_file.exists():
        from .production_settings import *
    del _production_settings_file

# Load local settings if available, these can override all other settings and are not tracked in version control
if _local_settings_file.exists():
    from .local_settings.settings import * # noqa: F401, F403
del _local_settings_file

if DEBUG:
    _debug_settings_file = LOCAL_SETTINGS_DIR / "debug_settings.py"
    if _debug_settings_file.exists():
        from .local_settings.debug_settings import *
    del _debug_settings_file
else:
    _production_settings_file = LOCAL_SETTINGS_DIR / "production_settings.py"
    if _production_settings_file.exists():
        from .local_settings.production_settings import *
    del _production_settings_file

if CSS_FRAMEWORK == 'bootstrap':
    from django_tinyuser.global_templates.bootstrap import PATH as BOOTSTRAP_TEMPLATES_PATH
    if 'DIRS' not in TEMPLATES[0]:
        TEMPLATES[0]['DIRS'] = []
    TEMPLATES[0]['DIRS'].insert(0, str(BOOTSTRAP_TEMPLATES_PATH))
elif CSS_FRAMEWORK == 'tailwindcss':
    from django_tinyuser.global_templates.trailwindcss import PATH as TAILWIND_TEMPLATES_PATH
    if 'DIRS' not in TEMPLATES[0]:
        TEMPLATES[0]['DIRS'] = []
    TEMPLATES[0]['DIRS'].insert(0, str(TAILWIND_TEMPLATES_PATH))

TEMPLATES[0]['DIRS'] = list(set(TEMPLATES[0]['DIRS']))

SETTINGS_MODULE = 'django_project.settings'
INSTALLED_APPS = tuple({
    *django_apps,
    *allauth_apps,
    *third_party_apps,
    *project_apps
})

del django_apps, allauth_apps, third_party_apps, project_apps
